### ISSUE TITLE
Crash when getting `tfe_outputs` with value `[null,null,null]`

### ISSUE THREAD

**Issue by arnodirlam** [hashicorp/terraform-provider-tfe#608]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.25.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/tfe v0.36.0
```

#### Terraform Configuration Files

```terraform
data "tfe_workspace_ids" "all" {
  organization = "my-org"
  tag_names    = [var.app_name]
}

data "tfe_outputs" "workspace" {
  count        = length(data.tfe_workspace_ids.all.ids)
  organization = "my-org"
  workspace    = element(keys(data.tfe_workspace_ids.all.ids), count.index)
}
```

#### Debug Output

```plaintext
...
data.tfe_outputs.workspace[5]: Reading...
data.tfe_outputs.workspace[5]: Read complete after 0s [id=my-org-ev2-pr-5108]
data.tfe_outputs.workspace[3]: Reading...
data.tfe_outputs.workspace[3]: Read complete after 0s [id=my-org-ev2-pr-5100]
data.tfe_outputs.workspace[2]: Reading...
data.tfe_outputs.workspace[2]: Read complete after 1s [id=my-org-ev2-pr-5099]
data.tfe_outputs.workspace[1]: Reading...
...

╷
│ Error: Request cancelled
│
│   with data.tfe_outputs.workspace[6],
│   on vpc.tf line 14, in data "tfe_outputs" "workspace":
│   14: data "tfe_outputs" "workspace" {
│
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with data.tfe_outputs.workspace[1],
│   on vpc.tf line 14, in data "tfe_outputs" "workspace":
│   14: data "tfe_outputs" "workspace" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│   with data.tfe_outputs.workspace[0],
│   on vpc.tf line 14, in data "tfe_outputs" "workspace":
│   14: data "tfe_outputs" "workspace" {
│
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with data.tfe_outputs.workspace[8],
│   on vpc.tf line 14, in data "tfe_outputs" "workspace":
│   14: data "tfe_outputs" "workspace" {
│
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with data.tfe_outputs.workspace[4],
│   on vpc.tf line 14, in data "tfe_outputs" "workspace":
│   14: data "tfe_outputs" "workspace" {
│
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with data.tfe_outputs.workspace[7],
│   on vpc.tf line 14, in data "tfe_outputs" "workspace":
│   14: data "tfe_outputs" "workspace" {
│
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-tfe_v0.36.0_x5 plugin:

panic: ElementKeyInt(0): invalid value tftypes.DynamicPseudoType<null> for tftypes.DynamicPseudoType

goroutine 40 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tftypes/value.go:278
github.com/hashicorp/terraform-plugin-go/tftypes.jsonUnmarshalTuple({0x140006b6600, 0x10, 0x40}, {0x140001accf0, 0x3, 0x3}, 0x140005c1620)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tftypes/value_json.go:434 +0xa60
github.com/hashicorp/terraform-plugin-go/tftypes.jsonUnmarshal({0x140006b6600, 0x10, 0x40}, {0x1052cc780, 0x140001acd20}, 0x140005c1620)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tftypes/value_json.go:58 +0x660
github.com/hashicorp/terraform-plugin-go/tftypes.ValueFromJSON(...)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tftypes/value_json.go:19
github.com/hashicorp/terraform-plugin-go/tfprotov5.RawState.Unmarshal({{0x140006b6600, 0x10, 0x40}, 0x0}, {0x1052cc780, 0x140001acd20})
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/state.go:73 +0xe4
github.com/hashicorp/terraform-provider-tfe/tfe.parseStateOutput(0x140006a80f0)
	github.com/hashicorp/terraform-provider-tfe/tfe/data_source_outputs.go:221 +0x1c4
github.com/hashicorp/terraform-provider-tfe/tfe.dataSourceOutputs.ReadDataSource({0x1400048e400}, {0x1052bf440, 0x140005bed40}, 0x1400038e500)
	github.com/hashicorp/terraform-provider-tfe/tfe/data_source_outputs.go:60 +0x414
github.com/hashicorp/terraform-provider-tfe/tfe.(*pluginProviderServer).ReadDataSource(0x140005be780, {0x1052bf440, 0x140005bed40}, 0x1400038e500)
	github.com/hashicorp/terraform-provider-tfe/tfe/plugin_provider.go:99 +0x9c
github.com/hashicorp/terraform-plugin-mux.SchemaServer.ReadDataSource({0x140005c7530, 0x140005c7560, {0x1400011b820, 0x2, 0x2}, 0x1400011ed00, 0x1}, {0x1052bf440, 0x140005bed40}, 0x1400038e500)
	github.com/hashicorp/terraform-plugin-mux@v0.2.0/schema_server.go:309 +0x80
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0x1400011ee00, {0x1052bf4e8, 0x14000298960}, 0x1400055e460)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:478 +0x37c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x10525b3c0, 0x1400011ee00}, {0x1052bf4e8, 0x14000298960}, 0x1400067a720, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140006daa80, {0x1052cf480, 0x14000682ea0}, 0x140006bb0e0, 0x140005c7620, 0x1058d5370, 0x0)
	google.golang.org/grpc@v1.43.0/server.go:1282 +0xc60
google.golang.org/grpc.(*Server).handleStream(0x140006daa80, {0x1052cf480, 0x14000682ea0}, 0x140006bb0e0, 0x0)
	google.golang.org/grpc@v1.43.0/server.go:1616 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x140001145e0, 0x140006daa80, {0x1052cf480, 0x14000682ea0}, 0x140006bb0e0)
	google.golang.org/grpc@v1.43.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.43.0/server.go:919 +0x1f0

Error: The terraform-provider-tfe_v0.36.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Also see: [Full trace log](https://gist.github.com/arnodirlam/b3ccca4ed241e67e321f479848bc5a23)

#### Expected Behavior

No crash.

#### Actual Behavior

It crashes.

#### Additional Context

The crash occurs both when running locally and in CI (GitHub Actions) using this setup step:

```yaml
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}
        terraform_wrapper: false
```

Thanks a lot for looking into it! :pray:

**Comment by arnodirlam** [comment]
Update: I poked around a bit and identified that it crashes for workspaces with an output value `[null,null,null]`.

**Comment by brandonc** [comment]
Thanks so much for reporting this! It looks like we were exposed to an upstream plugin bug since 0.34.0. We should be releasing a patch version a little later today.

**Comment by arnodirlam** [comment]
That's great to hear, thanks a lot for all the good work you all put into this! 🌻
