### ISSUE TITLE
TFE provider crashes for tfe_organization_membership

### ISSUE THREAD

**Issue by kaefferlein** [hashicorp/terraform-provider-tfe#995]
#### Terraform Cloud/Enterprise version

we are starting the terraform apply via github action. 
The terraform itself runs on Terraform Enterprise with version `v202307-1-dde54ba`

#### Terraform version

```plaintext
Terraform v1.5.1
on linux_amd64
```

#### Terraform Configuration Files

I am only providing the important settings:

```
# The versions.tf is used to specify the version requirements of the module
terraform {
  required_version = ">= 1.2.0, < 2"
  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "0.47.0" # until issue has been fixed https://github.com/MediaMarktSaturn/terraform-enterprise-orchestrator/actions/runs/5795669207/job/15710726516
    }
  }
}

...

// Add customer users to organization
resource "tfe_organization_membership" "members" {
  for_each     = local.tfe_org_members
  email        = each.key
  organization = local.tfe_org
}


```

#### Debug Output

```
Error: Plugin did not respond
│ 
│   with tfe_organization_membership.members["grulke@mediamarktsaturn.com"],
│   on members.tf line 5, in resource "tfe_organization_membership" "members":
│    5: resource "tfe_organization_membership" "members" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-tfe_v0.48.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc89e4]

goroutine 9954 [running]:
github.com/hashicorp/terraform-provider-tfe/tfe.resourceTFETeamProjectAccessRead({0x1067760, 0xc0001a1d40}, 0xc000678f80, {0xe3d0c0?, 0xc0000fc1e0?})
	github.com/hashicorp/terraform-provider-tfe/tfe/resource_tfe_team_project_access.go:314 +0x624
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003ba2a0, {0x1067798, 0xc000556a20}, 0xd?, {0xe3d0c0, 0xc0000fc1e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:750 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003ba2a0, {0x1067798, 0xc000556a20}, 0xc00016b110, {0xe3d0c0, 0xc0000fc1e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:1044 +0x59e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00019d500, {0x1067798?, 0xc000556900?}, 0xc000273480)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:616 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc0003c60f0, 0xc000359f80, 0xc0003c6120, 0xc0003c6150, {0xc0003ae3c0, 0x3, 0x4}}, {0x1067798?, 0xc0005565d0?}, 0xc000273480)
	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ReadResource.go:29 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00038ac80, {0x1067798?, 0xc0004a5bc0?}, 0xc0001a1aa0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:751 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xea0be0?, 0xc00038ac80}, {0x1067798, 0xc0004a5bc0}, 0xc0000ab1f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002521e0, {0x106cf20, 0xc000102340}, 0xc0001e1560, 0xc00046a1b0, 0x1615970, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0002521e0, {0x106cf20, 0xc000102340}, 0xc0001e1560, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-tfe_v0.48.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform plan (exit 1)
```

#### Expected Behavior

The run should succeed.

#### Actual Behavior

The run fails with a `plugin crashed` error

#### Additional Context

we are running the terraform apply via github action.
After pinning the version of the tfe_provider to 0.47.0 the run is successful again.

**Comment by sebasslash** [comment]
Even though this was reported first, l'm closing this issue since #996 pertains to the actual resource in question. Thanks for submitting this.
