### ISSUE TITLE
v0.48.0 crash for tfe_team_project_access and tfe_team_access

### ISSUE THREAD

**Issue by juicybaba** [hashicorp/terraform-provider-tfe#996]
#### Terraform Cloud/Enterprise version

 Terraform Enterprise v202307-1

#### Terraform version

```plaintext
v1.5.4
```

#### Terraform Configuration Files

```terraform
resource "tfe_team_access" "default" {
  access       = "write"
  team_id      = <team_id>
  workspace_id =  <workspace_id>
}

resource "tfe_team_project_access" "default" {
  project_id =  <project_id>
  team_id    = <team_id>
  access     = "admin"
}
```

#### Debug Output

```plaintext
Stack trace from the terraform-provider-tfe_v0.48.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc89e4]

goroutine 532 [running]:
github.com/hashicorp/terraform-provider-tfe/tfe.resourceTFETeamProjectAccessRead({0x1067760, 0xc0008d2de0}, 0xc000584d00, {0xe3d0c0?, 0xc00076e510?})
github.com/hashicorp/terraform-provider-tfe/tfe/resource_tfe_team_project_access.go:314 +0x624
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003f1ea0, {0x1067798, 0xc00039a3f0}, 0xd?, {0xe3d0c0, 0xc00076e510})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:750 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003f1ea0, {0x1067798, 0xc00039a3f0}, 0xc000365c70, {0xe3d0c0, 0xc00076e510})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:1044 +0x59e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00020ee88, {0x1067798?, 0xc00039a2d0?}, 0xc000251480)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:616 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc0003ddec0, 0xc00040c100, 0xc0003ddef0, 0xc0003ddf20, {0xc0003b2cc0, 0x3, 0x4}}, {0x1067798?, 0xc000997f50?}, 0xc000251480)
github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ReadResource.go:29 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003bd900, {0x1067798?, 0xc0009977a0?}, 0xc0008d2ba0)
github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:751 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xea0be0?, 0xc0003bd900}, {0x1067798, 0xc0009977a0}, 0xc000224c40, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00028c1e0, {0x106cf20, 0xc0001401a0}, 0xc00072e120, 0xc000411f80, 0x1615970, 0x0)
google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc00028c1e0, {0x106cf20, 0xc0001401a0}, 0xc00072e120, 0x0)
google.golang.org/grpc@v1.56.1/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-tfe_v0.48.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

#### Expected Behavior

The code should work.
#### Actual Behavior

The code works with `v0.47.0` but not wirh `v0.48.0`
#### Additional Context

Although the impact resources are different, my issue looks very similar to https://github.com/hashicorp/terraform-provider-tfe/issues/995.

**Comment by sebasslash** [comment]
Thanks so much for reporting this. It seems like the new changes aren't TFE version aware, hence why the plugin panics when the `project-access` field is not returned by the API. I will patch fix this, in the meantime downgrading to v0.47.0 will work.

**Comment by sebasslash** [comment]
Another heads up, this feature is available in the `v202308-1` release. If upgrading the instance is an option for you, you'll be able to upgrade back to v0.48.0.

**Comment by juicybaba** [comment]
> Another heads up, this feature is available in the `v202308-1` release. If upgrading the instance is an option for you, you'll be able to upgrade back to v0.48.0. 

@sebasslash Thanks for the update, will keep that in mind. Other than the resources I reported, is there any other resources get impacted?
